import { env, exports } from 'cloudflare:workers';
import { evictDurableObject, runInDurableObject } from 'cloudflare:test';
import { test, expect, afterEach } from 'vitest';
const clients=[];
const token='test-only-capability-0123456789abcdef';
const stub=()=>env.RELAY.get(env.RELAY.idFromName(env.RELAY_NAMESPACE));
async function request(id,room='nightsky-test',options={}){const u=new URL('https://relay.test/');Object.entries({token,room,id,...options.query}).forEach(([k,v])=>u.searchParams.set(k,v));const headers={Upgrade:'websocket','CF-Connecting-IP':options.ip||'127.0.0.1'};if(options.origin!==null)headers.Origin=options.origin??'https://tonk.network';const response=await exports.default.fetch(u.href,{headers});if(response.status!==101)await response.text();return response;}
async function connect(id,room,options){const r=await request(id,room,options);expect(r.status).toBe(101);const ws=r.webSocket,queue=[],waiters=[];ws.addEventListener('message',e=>{const m=JSON.parse(e.data);const i=waiters.findIndex(w=>w.p(m));if(i>=0){const w=waiters.splice(i,1)[0];clearTimeout(w.timer);w.resolve(m);}else queue.push(m);});const closed=new Promise(resolve=>ws.addEventListener('close',e=>{try{ws.close(e.code===1005?1000:e.code);}catch{}resolve(e);},{once:true}));ws.accept();const c={ws,queue,closed,send:m=>ws.send(typeof m==='string'?m:JSON.stringify(m)),next(p){const i=queue.findIndex(p);if(i>=0)return Promise.resolve(queue.splice(i,1)[0]);return new Promise((resolve,reject)=>{const w={p,resolve,timer:setTimeout(()=>{waiters.splice(waiters.indexOf(w),1);reject(new Error('message timeout'));},2000)};waiters.push(w);});}};clients.push(c);c.peers=await c.next(m=>m.type==='peers');return c;}
const signal={type:'signal',to:'b',payload:{sdp:{type:'offer',sdp:'v=0\r\n'}}};
afterEach(async()=>{const own=clients.splice(0);for(const c of own)try{c.ws.close(1000);}catch{}await Promise.all(own.map(c=>c.closed));});
test('health, capability and origin gates before allocation',async()=>{expect(await (await exports.default.fetch('https://relay.test/health')).json()).toEqual({ok:true});for(const options of [{query:{token:''}},{query:{token:'wrong'}},{origin:'https://evil.test'},{origin:null}])expect((await request('a',undefined,options)).status).toBe(403);expect((await request('a','invalid')).status).toBe(400);await connect('a',undefined,{origin:'null'});});
test('two peers, duplicate incumbent survives, room isolation and malformed sender safety',async()=>{const a=await connect('a'),b=await connect('b');expect(b.peers.peers.map(p=>p.id)).toEqual(['a']);expect((await request('a')).status).toBe(409);a.send({type:'ping',t:1});expect((await a.next(m=>m.type==='pong')).t).toBe(1);a.send(signal);expect((await b.next(m=>m.type==='signal')).from).toBe('a');const foreign=await connect('b','nightsky-other');a.send(signal);await b.next(m=>m.type==='signal');expect(foreign.queue.some(m=>m.type==='signal')).toBe(false);a.send({type:'signal',to:'b',payload:{a:[[[[]]]]}});await a.closed;b.send({type:'ping',t:2});expect((await b.next(m=>m.type==='pong')).t).toBe(2);});
test('actual runtime hibernation restores sockets, membership and buckets without duplicate joins',async()=>{const a=await connect('a'),b=await connect('b');await a.next(m=>m.type==='join');for(let t=0;t<10;t++)a.send({type:'ping',t});await a.next(m=>m.type==='pong'&&m.t===9);const old=await runInDurableObject(stub(),i=>({generation:i.generation,tokens:[...i.sockets.values()].find(x=>x.id==='a').tokens}));await evictDurableObject(stub());a.send(signal);await b.next(m=>m.type==='signal');const fresh=await runInDurableObject(stub(),i=>({generation:i.generation,tokens:[...i.sockets.values()].find(x=>x.id==='a').tokens,size:i.sockets.size}));expect(fresh.generation).not.toBe(old.generation);expect(fresh.size).toBe(2);expect(fresh.tokens).toBeLessThan(119);expect(b.queue.filter(m=>m.type==='join')).toHaveLength(0);const c=await connect('c');expect(c.peers.peers.map(p=>p.id).sort()).toEqual(['a','b']);a.ws.close(1000);await b.next(m=>m.type==='leave'&&m.id==='a');expect(b.queue.filter(m=>m.type==='leave'&&m.id==='a')).toHaveLength(0);});
test('runtime restart closes transport; same identities reconnect and signal',async()=>{const a=await connect('a'),b=await connect('b');await evictDurableObject(stub(),{webSockets:'close'});await Promise.all([a.closed,b.closed]);const aa=await connect('a'),bb=await connect('b');aa.send(signal);await bb.next(m=>m.type==='signal');});
test('binary, oversized and primitive payloads close sender; service survives',async()=>{for(const payload of [new Uint8Array([1,2]),'x'.repeat(32769),'null','[]']){const a=await connect('a');a.ws.send(payload);await a.closed;}const b=await connect('b');b.send({type:'ping',t:7});await b.next(m=>m.type==='pong');});
test('peer limit and rate limit are enforced',async()=>{for(let n=0;n<32;n++)await connect('p'+n);expect((await request('extra')).status).toBe(429);const a=clients[0];await runInDurableObject(stub(),i=>{const [ws,m]=[...i.sockets].find(([,x])=>x.id==='p0');m.tokens=0;m.last=Date.now()+60000;ws.serializeAttachment(m);});a.send({type:'ping',t:1});await a.closed;});
test('bounded dynamic rooms, total sockets and per-IP connections',async()=>{for(let n=0;n<64;n++)await connect('x','nightsky-r'+n,{ip:'192.0.2.'+(n+1)});expect((await request('x','nightsky-over',{ip:'198.51.100.1'})).status).toBe(429);for(let n=0;n<192;n++)await connect('p'+n,'nightsky-r'+(n%64),{ip:'198.51.100.'+(n%250+1)});expect((await request('last','nightsky-r0',{ip:'203.0.113.1'})).status).toBe(429);});
test('recipient budget rejects offending sender without killing its target',async()=>{const a=await connect('a'),b=await connect('b');await runInDurableObject(stub(),i=>{const [ws,meta]=[...i.sockets].find(([,x])=>x.id==='b');meta.outTokens=0;meta.outLast=Date.now()+60000;ws.serializeAttachment(meta);});a.send(signal);await a.closed;await runInDurableObject(stub(),i=>{const [ws,meta]=[...i.sockets].find(([,x])=>x.id==='b');meta.outTokens=131072;meta.outLast=Date.now();ws.serializeAttachment(meta);});b.send({type:'ping',t:9});await b.next(m=>m.type==='pong');});
test('maximum UTF-8 roster fits outbound cap without phantom joins',async()=>{for(let n=0;n<31;n++)await connect(String(n)+'界'.repeat(125),undefined,{query:{tag:'界'.repeat(128),name:'界'.repeat(128)}});const last=await connect('last');expect(last.peers.peers.length).toBe(31);expect(new TextEncoder().encode(JSON.stringify(last.peers)).length).toBeGreaterThan(32768);last.send({type:'ping',t:11});await last.next(m=>m.type==='pong');});
test('per-IP cap applies across different rooms',async()=>{for(let n=0;n<32;n++)await connect('x','nightsky-ip'+n,{ip:'192.0.2.99'});expect((await request('x','nightsky-ipover',{ip:'192.0.2.99'})).status).toBe(429);await connect('x','nightsky-ipover',{ip:'192.0.2.100'});});
test('stale auth-epoch attachment is rejected after actual hibernation',async()=>{const a=await connect('a');await runInDurableObject(stub(),i=>{const [ws,m]=[...i.sockets][0];m.epoch='retired-epoch';ws.serializeAttachment(m);});await evictDurableObject(stub());const b=await connect('b');await a.closed;expect(b.peers.peers).toEqual([]);});
